config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  post 'driver' => 'drivers#index'

  namespace :api do
    namespace :v1, defaults: {format: :json } do
      resources :searches, only: [:show, :index]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/current_driver.rb
class CurrentDriver < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :team, presence: true
end

app/models/driver.rb
class Driver < ApplicationRecord

  def self.service
    @@service ||= F1SearchService.new
  end

  def self.error_handling(input)
    input[:player].nil? ? 'Error' : input
  end

  def self.output_parse(name)
    name[:player].first
  end

  def self.banner_parse(string)
    image = output_parse(string)
    image[:strBanner]
  end

  def self.driver_name(string)
    name = output_parse(string)
    name[:strPlayer]
  end

  def self.nationality(string)
    nation = output_parse(string)
    nation[:strNationality]
  end

  def self.team(string)
    team = output_parse(string)
    team[:strTeam]
  end

  def self.thumb_img(string)
    image = output_parse(string)
    image[:strThumb]
  end

  def self.birth_location(string)
    location = output_parse(string)
    location[:strBirthLocation]
  end

  def self.description_en(string)
    description = output_parse(string)
    description[:strDescriptionEN]
  end
end

app/models/search.rb
class Search < ApplicationRecord
end

app/controllers/api/v1/searches_controller.rb
class Api::V1::SearchesController < ApplicationController
  respond_to :json

  def show
    respond_with Search.find(params[:id])
  end

  def index
    respond_with Search.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController
  def index
    driver = params[:driver]
    if driver.nil?
      flash[:danger] = 'No driver found by that name, please try again'
    else
      @output = Driver.service.get_driver_search(driver)
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @drivers = CurrentDriver.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/drivers/index.html.erb
  <% if Driver.error_handling(@output) == 'Error' %>
    <h2>Sorry! We didn't find that driver, please search again!</h2>
    <%= link_to 'Home', '/' %>
  <% else %>
    <%= render 'layouts/driver' %>
  <%= link_to 'Search another driver', root_path %>
<% end %>

app/views/home/index.html.erb
<h1>Formula 1 Driver DB</h1>

<p>Want an indepth dive about your favorite Formula 1 driver? Search below!</p>
<p>Ex driver:Kimi Raikkonen </p>

<%= form_tag driver_path, :method => 'POST' do %>
  <div class="form-group">
    <%= text_field_tag 'driver', nil, placeholder: "Driver Name", class: "form-group" %>
      <%= submit_tag "Search", class: "btn btn-outline-success" %>
<% end %>

<p>Or you can search from the list below</p>
  <ul>
    <% @drivers.each do |driver| %>
    <li><%= driver.name.titleize %></li>
    <%= form_tag driver_path, :method => 'POST' do %>
        <%= hidden_field 'driver', nil, :value => driver.name, class: "form-group" %>                    
      <%= submit_tag "Driver Details", class: "btn" %> 
    <% end %>
  <% end %>

app/views/layouts/_driver.html.erb
 <%= image_tag(Driver.banner_parse(@output))%>
  <ul>
    <li>Name: <%= Driver.driver_name(@output) %></li>
    <li>Nation: <%= Driver.nationality(@output) %></li>
    <li>Birth location:<%= Driver.birth_location(@output) %></li>
    <li>Team: <%= Driver.team(@output) %></li>
    <li>About: <%= Driver.description_en(@output) %></li>
  </ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>F1Database</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>